### ISSUE TITLE
The website example needs a change to work in playground

### ISSUE THREAD

**Issue by fgm** [vardius/message-bus#10]
The "message-bus" import is eliminated when ran from play.golang.org, as it doesn't match the package name as used by the code. It needs to be aliases, as in https://play.golang.org/p/U5nstd936qf

**Comment by vardius** [comment]
thanks for pr, sorry for late update but i just noticed notification

**Comment by vardius** [comment]
please close this issue if all good now ;)

**Comment by fgm** [comment]
The PR is fine, but the site does not seem to have been updated yet (caching ? not pushed ?)

**Comment by fgm** [comment]
I'm afraid it didn't succeed at publishing
![Capture d’écran 2021-01-14 à 09 45 08](https://user-images.githubusercontent.com/143311/104565939-50066900-564d-11eb-9ce0-44ad751e43c8.png)

**Comment by vardius** [comment]
It did work, basic example page you update is this one here
https://rafallorenz.com/message-bus/docs/basic-example

<img width="824" alt="image" src="https://user-images.githubusercontent.com/6569206/104573913-94275700-56a9-11eb-80a4-d3896ea5c0de.png">

**Comment by vardius** [comment]
The code snippet on the home page is the one here
https://github.com/vardius/message-bus/blob/master/website/src/pages/en/index.js#L18

**Comment by fgm** [comment]
Oh, so that's another one that needs updating then.

**Comment by vardius** [comment]
updated, will close this issue, reopen if needed
