### ISSUE TITLE
Could you keep the 'v1.0.0' interface? 

### ISSUE THREAD

**Issue by michilu** [vardius/message-bus#2]
I like the new interface. Really, I used the semaphore to control concurrency outside the bus.
And, I hope to keeps both the old interface and the new interface.
- There is the code that depends on the old interface.
- The new interface has a concern as performance is degraded. https://github.com/vardius/message-bus/blob/master/README.md#benchmark

`v1.0.0` https://github.com/vardius/message-bus/blob/c1f01b61c37e8992775c53d6be6b61e362adfce2/bus.go#L82

`v1.1.0` https://github.com/vardius/message-bus/blob/bdb2394d9af1cf4f226490d32a6cb4e8f6d36ab7/bus.go#L93

Ref: https://github.com/vardius/message-bus/commit/dd40db9f8e8a2cfe434fdc9381202827f851c931#diff-ecf9c6bcdc8d97b7f04226e8857c1108L82

**Comment by carldunham** [comment]
Heh. I was going to suggest the opposite, that current interface stutters quite a bit. My concern is more aesthetic tho, as Go Stockholm Syndrome kicks in.

**Comment by vardius** [comment]
The main goal for `v1.1.0` was to reduce the amount of goroutine spawns. By spawning goroutines on subscribe once and keeping them alive. In previous versions many goroutines where spawned each time publish method was called.

Also earlier the concurrency was limited on a global level meaning one queue per all handler of all topics. in `v1.1.0` it is limited per topic. Each of topics has it's own queue.

I encourage you to contribute. I am sure together we can workout best performance interface. More use cases gives more insides on actual message-bus usability and performance.

**Comment by michilu** [comment]
@vardius Thanks for your reply.
I will think about your suggestion.

My use case that implements with your message-bus is this.
https://github.com/michilu/boilerplate/blob/173e4736f68c188a6300f4a87f8c3de276dddce6/v/bus/bus.go

I want to use a lightweight pub/sub.
Now I implement by channel via genny, like this.
https://github.com/michilu/boilerplate/blob/master/v/topic/topic.go

If you no problem, close this issue.

**Comment by vardius** [comment]
Would be good to know what is the opinion of other ppl as well.

As to your request we could add new constructor something like this

```go
// NewAsync creates new MessageBus that always spawns goroutines
func NewAsync() MessageBus {
	return &messageBus{
		handlerQueueSize: runtime.NumCPU(),
		handlers:         make(handlersMap),
	}
}
```

which would create new bus with preset number of concurrent calls. maybe we could set it to -1 and then not use buffered channels but call handler directly ?

ideally we create strategy interface (async, sync) and based on that we use buffered channels ?
what do you think ?

**Comment by vardius** [comment]
I’m closing this issue because it has been inactive for a while. Please use the https://github.com/vardius/message-bus/releases/tag/v1.0.0 for *v1.0.0* interface. Keep in mind that by using older release you loose recent bug fixes and futures.

Thank you!
