### ISSUE TITLE
Unsubscribe error

### ISSUE THREAD

**Issue by lafer-m** [vardius/message-bus#8]
can't use  Unsubscribe(Astruct.Foo), this can be supported?

**Comment by lafer-m** [comment]
@vardius

**Comment by vardius** [comment]
Hi @lafer-m how urgent is it for you? can this w8 till weekend ?
Haven't tried case like that, would be good to add a test and make it work, I could sit on it on Saturday or Sunday unless you are in a rush then I could have a look tmr evening, but I am not sure how much time would it take.

Do you feel like adding a test with multiple different cases ?

**Comment by lafer-m** [comment]
i try to used some stuct's method to subscribe, but i found can't delete handler in Unsubscribe  ,  I'm still anxious, pls help me.   i am new to golang,  thank you very much.  this is my test case https://play.golang.org/p/LmGN3h-lNiX ;

**Comment by vardius** [comment]
I suppose you would have to assign it to variable like this https://play.golang.org/p/dCPrSQr0I_j
and then it should work

**Comment by lafer-m** [comment]
thank you. @vardius
